### ISSUE TITLE
Error on pip installation

### ISSUE THREAD

**Issue by HarryRogers0** [santoshlite/EigenLedger#122] opened 2024-03-17 21:15 UTC
**Describe the bug**
When installing the module using `pip install empyrial` I get the following error
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
**To Reproduce**
Run `pip install empyrial`

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Visual Studio

**Comment by localperf** [comment] 2024-05-26 17:28
I am having the same problem on 5/26/2024.

**Comment by orenvor** [comment] 2024-06-08 18:38
This is caused by the dependency in empyrical library, see related bug in:
https://github.com/quantopian/empyrical/issues/139

**Comment by BigFav** [comment] 2024-07-30 03:05
Plus one on this. This issue blocks people from being able to use the package easily and effectively.

**Comment by kullark** [comment] 2024-09-12 18:54
same error with the install on mac os:

        File "/private/var/folders/b0/sy_vsjv502x55ztflt6wy3740000gn/T/pip-install-rt2j06nw/empyrical_a09e93f86beb4e1588acba0ead632e28/versioneer.py", line 1473, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/b0/sy_vsjv502x55ztflt6wy3740000gn/T/pip-install-rt2j06nw/empyrical_a09e93f86beb4e1588acba0ead632e28/versioneer.py", line 1406, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b0/sy_vsjv502x55ztflt6wy3740000gn/T/pip-install-rt2j06nw/empyrical_a09e93f86beb4e1588acba0ead632e28/versioneer.py", line 412, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Praj-17** [comment] 2024-10-01 11:19
Is this Project Abudoned then? The same issue still persists. @santoshlite

**Comment by Praj-17** [comment] 2024-10-03 14:17
Hi , @santoshlite  do you have any update with this, else does any other version currently works? so I can get started?

**Comment by santoshlite** [comment] 2024-10-04 05:37
Hey @Praj-17, while working on it I noticed another bug I need to fix... Hoping on releasing a fix by Monday!

**Comment by santoshlite** [comment] 2024-11-09 01:05
Sorry for the long long delay but it has been fixed now. Empyrical is no longer maintained and it started to be a problem so I needed to fix it + bundle it with our library. I updated some things to make it work but you should be able to run the quickstart here & build from there: https://colab.research.google.com/drive/1TyNgudyFcsgob7o49PwfDJHLaHvluxaU?usp=sharing

happy hacking :)

**Closed by santoshlite** 2024-11-09 01:05 UTC

**Comment by santoshlite** [comment] 2024-11-09 01:13
check #128 for more details about `empyrical` will be bundled with us from now on
